name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      working-directory: src
      run: dotnet restore SchoolBookingApp.sln

    - name: Install Windows desktop workload
      run: dotnet workload install windowsdesktop

    - name: Build
      working-directory: src
      run: dotnet build SchoolBookingApp.sln --no-restore --configuration Release

    - name: Test
      working-directory: src
      run: dotnet test SchoolBookingApp.sln --no-build --verbosity normal
