name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      working-directory: src
      run: dotnet restore SchoolBookingApp.sln

    - name: Build
      working-directory: src
      run: dotnet build SchoolBookingApp/SchoolBookingApp.csproj --no-restore --configuration Release

    - name: Test
      working-directory: src
      run: |
        dotnet build SchoolBookingAppTests/SchoolBookingAppTests.csproj --no-restore --configuration Release
        dotnet test SchoolBookingAppTests/SchoolBookingAppTests.csproj --no-build --verbosity normal
